version: 2.1

commands:
    build-n-test:
        steps:
            - run:
                  name: Display version
                  command: npm version
            - checkout
            - node/install-packages:
                  pkg-manager: yarn
            - restore_cache:
                  keys:
                      - v{{ .Environment.CIRCLE_CACHE_VERSION }}-{{ arch }}-npm-cache-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}
                      - v{{ .Environment.CIRCLE_CACHE_VERSION }}-{{ arch }}-npm-cache-master-{{ .Environment.CIRCLE_JOB }}
            - run:
                  name: Install dependencies
                  command: yarn ci
            - run:
                  name: Run tests
                  command: yarn test
    save-npm-lock:
        steps:
            - save_cache:
                  key: v{{ .Environment.CIRCLE_CACHE_VERSION }}-{{ arch }}-npm-lock-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "yarn.lock" }}
                  paths:
                      - node_modules
    save-npm-cache:
        steps:
            - save_cache:
                  key: v{{ .Environment.CIRCLE_CACHE_VERSION }}-{{ arch }}-npm-cache-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "yarn.lock" }}
                  paths:
                      - ~/.npm/_cacache

jobs:
    node-v14-test:
        docker:
            - image: node:14
        steps:
            - build-n-test
    node-v16-test:
        docker:
            - image: node:16
        steps:
            - build-n-test
    node-v18-test:
        docker:
            - image: node:18
        steps:
            - build-n-test

workflows:
    node-multi-build:
        jobs:
            - node-v14-test
            - node-v16-test
            - node-v18-test
